version: 2
project_name: keycloak-ssh-auth

release:
  github:
    owner: siegy22
    name: keycloak-ssh-auth

builds:
  - id: keycloak-ssh-auth
    main: ./main.go
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

dist: dist

archives:
  - formats: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: desc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
